### ISSUE TITLE
GROMACS / AMBER Protein Ligand Complex MD Setup error

### ISSUE THREAD

**Issue by mglgc** [bioexcel/biobb_websites#2]
Hi,
Both the GROMACS and AMBER Protein Ligand Complex MD Setup workflows cannot load the .lib and .frcmod Amber files in order to keep the ligand. They are getting hung up trying to load such a files.
Thank you very much in advance for the reply.

**Comment by gbayarri** [comment]
Hi, I assume that you are talking of the biobb workflows website, this one:

https://mmb.irbbarcelona.org/biobb-wfs/

Can you please provide more information? We have tested it and it seems to work properly:

Uplaod of .lib and .fcrmod files:

![Screenshot 2023-06-07 at 11 00 22](https://github.com/bioexcel/biobb_websites/assets/19928100/b7bf49a4-7284-4fc9-8266-1ba2e9fc6938)

Once both files are uploaded, click Check button and a new modal window will be shown:

![Screenshot 2023-06-07 at 11 00 40](https://github.com/bioexcel/biobb_websites/assets/19928100/4358430e-b65d-45d7-8fd2-fbd450f4b575)

Let me know if you are following these steps.

**Comment by mglgc** [comment]
Right, I'm talking about the biobb workflows website. After selecting both the .lib and .frcmod files for the ligand (indeed built with the corresponding biobb workflow module for ligand parameterization), the lib button remains in an endless uploading state (screenshot enclosed).
Thank you.

![Screenshot from 2023-06-07 14-11-43](https://github.com/bioexcel/biobb_websites/assets/52656151/96aa885f-bf3b-4c8b-844f-beb5eb1d84fb)

**Comment by gbayarri** [comment]
Can you provide me all the data for reproducing your workflow? 

1. Both the .lib and .frcmod files
2. PDB id / assembly or input file

Input data for the biobb ligand parameterization workflow would be welcomed as well.

**Comment by mglgc** [comment]
Attached you will find all the files you are requering. Thank you very much in advance for your replies.Regards.

    En miércoles, 7 de junio de 2023 14:19:39 CEST, Genís Bayarri ***@***.***> escribió:  
 
 


Can you provide me all the data for reproducing your workflow?
   
   - Both the .lib and .frcmod files
   - PDB id / assembly or input file

Input data for the biobb ligand parameterization workflow would be welcomed as well.

**Comment by mglgc** [comment]
En miércoles, 7 de junio de 2023 21:12:52 CEST, Mario Garcia ***@***.***> escribió:  
 
  
Attached you will find all the files you are requering. Thank you very much in advance for your replies.Regards.

    En miércoles, 7 de junio de 2023 14:19:39 CEST, Genís Bayarri ***@***.***> escribió:  
 
 


Can you provide me all the data for reproducing your workflow?
   
   - Both the .lib and .frcmod files
   - PDB id / assembly or input file

Input data for the biobb ligand parameterization workflow would be welcomed as well.

**Comment by gbayarri** [comment]
Hi, I'm afraid I didn't receive anything.

Can you upload these files somewhere and provide me the link? If you're not able, please copy and paste the content here.

Thanks.

**Comment by mglgc** [comment]
Dear Genis,
I sent them yesterday in a subsequent email after the former one. Anyway, I'm attaching them again now (the lib file is zip compressed for a compatibility issue with my mail reader).
Thank you very much for your support and help.Regards.

    En jueves, 8 de junio de 2023 8:28:44 CEST, Genís Bayarri ***@***.***> escribió:  
 
 


Hi, I'm afraid I didn't receive anything.

Can you upload these files somewhere and provide me the link? If you're not able, please copy and paste the content here.

Thanks.

**Comment by gbayarri** [comment]
Hi @mglgc ,

You are trying to attach a file sending it via e-mail, please do it on the comment box in the issue following this tutorial:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Thanks.

**Comment by mglgc** [comment]
Here they are. Thank you.

[biobb.LigandParam.output.frcmod.zip](https://github.com/bioexcel/biobb_websites/files/11686102/biobb.LigandParam.output.frcmod.zip)
[biobb.LigandParam.output.lib.zip](https://github.com/bioexcel/biobb_websites/files/11686103/biobb.LigandParam.output.lib.zip)
[complex.pdb.zip](https://github.com/bioexcel/biobb_websites/files/11686104/complex.pdb.zip)
[ligand.pdb.zip](https://github.com/bioexcel/biobb_websites/files/11686106/ligand.pdb.zip)

**Comment by gbayarri** [comment]
Hi @mglgc

The process was not working due to technical problems, they should be fixed by now. 

On the other hand, the .lib and the .pdb files provided by you have different heteroatom names (**UNL** and **LIG**). This problem happens because acpype (the tool behind the ligand parameterization workflow) sometimes changes the name of the ligand. Please be sure that both of them have the same name **LIG** as this is the one of the complex.pdb file (be aware that there are several occurrences of **UNL** in the .lib file). Otherwise the workflow will crash.

Besides, remember to map the atoms (second image in [my first answer](https://github.com/bioexcel/biobb_websites/issues/2#issuecomment-1580453373) to this thread). This is important, because after the parameterization, some atoms might have changed their names. Additionally, for the GROMACS workflow, you must be sure that the parameters preserve their original coordinates.

Let me know if it has worked for you.

**Comment by adamhospital** [comment]
Hi @mglgc

We have played with the GROMACS and AMBER Protein Ligand Complex MD Setup workflows and the input files you sent to us. Here you have the results, just in case they are useful for you.

https://mmb.irbbarcelona.org/biobb-wfs/structure/output/summary/6481ee4f9ebad1.16507855

https://mmb.irbbarcelona.org/biobb-wfs/structure/output/summary/6482f3de860c86.01288592

Hope it helps!

**Comment by mglgc** [comment]
Dear Adam,
Thank you very much for all these results and your support.Best regards!
   Mario.

    En miércoles, 14 de junio de 2023 12:18:00 CEST, Adam Hospital Gasch ***@***.***> escribió:  
 
 


Hi @mglgc

We have played with the GROMACS and AMBER Protein Ligand Complex MD Setup workflows and the input files you sent to us. Here you have the results, just in case they are useful for you.

https://mmb.irbbarcelona.org/biobb-wfs/structure/output/summary/6481ee4f9ebad1.16507855

https://mmb.irbbarcelona.org/biobb-wfs/structure/output/summary/6482f3de860c86.01288592

Hope it helps!

**Comment by evelydnts** [comment]
Olá bom dia! estou enfrentando o mesmo problema. Quando envio os arquivos, esta carregando infinitamente e ja tentei as soluções presentes aqui, porém mesmo assim não carrega os parametros. Obrigada!

**Comment by adamhospital** [comment]
Dear evelydnts,

we are sorry about this problem. We are experiencing technical problems lately. We have been able to reproduce the issue and will work on it as soon as possible. In the meantime, please remember that our workflows are also available in different "flavours", such as Jupyter Notebook and Pure Python. Please take a look at the [BioBB demonstration workflows](https://mmb.irbbarcelona.org/biobb/workflows) website and the [BioBB Workflows](https://github.com/bioexcel/biobb_workflows) repository. 

Hope this helps!

Best regards,

-Adam-
